services:
  mongodb:
    image: mongo:7.0.7
    ports:
      - 27017:27017
    volumes:
      - db:/data:/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    container_name: wishlist-db
    networks:
      - wishlist-network

  wishlist:
    depends_on:
      - mongodb
    build:
      context: .
    restart: on-failure
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_MONGODB_URI=mongodb://rootuser:rootpass@mongodb/wishlist-db?authSource=admin
    ports:
      - 8080:8080
    networks:
      - wishlist-network

volumes:
  db:

networks:
  wishlist-network:
    driver: bridge